# https://goreleaser.com
version: 2

builds:
  - id: osaudit
    main: ./cmd/osaudit
    binary: osaudit
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "osaudit_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE
